run:
	./linux_x86.sh
	huawei-checker astList.txt config.json

clean:
	-rm astList.txt time.txt MOLINT.TAINTED.MEM.OP.xml REFERABLE.REPAIR.MISSING.CHECK.xml
	-rm Label_Feature_Data.xml DataSet.txt
	-rm -rf obj
